In [19]:
import random
random.seed(42)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [21]:
# loading the data 

data = pd.read_csv('Material de apoio para avaliação - Vehicle/Vehicle.csv')
print(data.head(10))

FileNotFoundError: [Errno 2] No such file or directory: 'Material de apoio para avaliação - Vehicle/Vehicle.csv'

In [ ]:
# looking for missing data

data.isnull().sum().sort_values(ascending=False).head(10)

Comp            0
Sc.Var.Maxis    0
Holl.Ra         0
Kurt.Maxis      0
Kurt.maxis      0
Skew.maxis      0
Skew.Maxis      0
Ra.Gyr          0
Sc.Var.maxis    0
Max.L.Rect      0
dtype: int64

In [ ]:
# no missing items

# storing the classes names and feature names
classes = np.array(pd.unique(data[data.columns[-1]]), dtype=str)
features_name = data.columns[:-1]

print(classes)
print(features_name)


['van' 'saab' 'bus' 'opel']
Index(['Comp', 'Circ', 'D.Circ', 'Rad.Ra', 'Pr.Axis.Ra', 'Max.L.Ra', 'Scat.Ra',
       'Elong', 'Pr.Axis.Rect', 'Max.L.Rect', 'Sc.Var.Maxis', 'Sc.Var.maxis',
       'Ra.Gyr', 'Skew.Maxis', 'Skew.maxis', 'Kurt.maxis', 'Kurt.Maxis',
       'Holl.Ra'],
      dtype='object')


In [ ]:
# Preparing the data

data = data.to_numpy()
nrow, ncol = data.shape
y =  data[:, -1]
X = data[:, 0:ncol-1]



[[95 48 83 ... 16 187 197]
 [91 41 84 ... 14 189 199]
 [104 50 106 ... 9 188 196]
 ...
 [106 54 101 ... 4 187 201]
 [86 36 78 ... 25 190 195]
 [85 36 66 ... 18 186 190]]


In [14]:
# Normalizing the data

scaler = StandardScaler().fit(X)
X = scaler.transform(X)



NameError: name 'X' is not defined

In [11]:
# Splitting the data

p = 0.2 # % of elements on test

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=p, random_state=42)

#training the Random Forest Model
rf = RandomForestClassifier(random_state=42)
rf.fit(x_train, x_test)

NameError: name 'X' is not defined